/**
 * Central application configuration. Single source of truth for tunable
 * constants so the rest of the app stays declarative.
 */
export const APP_CONFIG = {
  name: "HH Goa 2026 Builder Generator",
  shortName: "HH Goa 2026",
  edition: "Goa · 2026",
  hashtag: "FrameInGoa",
  shareText:
    "🚀 Excited to build at HH Goa 2026!\n\nJust created my Builder Identity.\n\nHH Goa 2026, let's build something worth remembering. 🌴⚡\n\n#FrameInGoa #HHGoa2026",
  downloadFileName: "hh-goa-builder-card.png",
  outputSize: 1080,
  /** Maximum upload size in bytes (12 MB). */
  maxUploadBytes: 12 * 1024 * 1024,
  /** Allowed MIME types in the file picker. */
  acceptedMimeTypes: [
    "image/jpeg",
    "image/png",
    "image/webp",
    "image/heic",
    "image/heif",
  ] as const,
  /** Allowed file extensions for the picker accept attr (lowercase, with dot). */
  acceptedExtensions: [".jpg", ".jpeg", ".png", ".webp", ".heic", ".heif"] as const,
  /** localStorage key for the persisted draft. */
  storageKey: "hh-goa-2026:draft:v1",
  /** Twitter / X username for the share intent target (used in via param). */
  twitterHandle: "hhgoa",
} as const;

/** Twitter share URL with prefilled text. */
export function buildTwitterShareUrl(text: string): string {
  const params = new URLSearchParams({
    text,
  });
  return `https://twitter.com/intent/tweet?${params.toString()}`;
}

/**
 * 100+ unique, original Builder Titles. Carefully curated to feel fresh,
 * non-repetitive, and aligned with the HH Goa builder/hacker/startup vibe.
 * The generator pulls from this list without immediately repeating.
 */
export const BUILDER_TITLES: readonly string[] = [
  "AI Explorer",
  "Cloud Architect",
  "DevOps Ninja",
  "Startup Hacker",
  "Prompt Engineer",
  "Code Wizard",
  "Infrastructure Hacker",
  "Builder of Tomorrow",
  "Open Source Hero",
  "Full Stack Builder",
  "Automation Architect",
  "Cloud Native Builder",
  "ML Explorer",
  "Frontend Crafter",
  "Backend Architect",
  "Product Engineer",
  "Systems Sculptor",
  "Data Cartographer",
  "Edge Computing Pioneer",
  "Reliability Engineer",
  "Platform Builder",
  "Design Engineer",
  "DX Craftsperson",
  "WebGL Voyager",
  "Shader Alchemist",
  "Embedded Dreamer",
  "Kernel Tinkerer",
  "Protocol Designer",
  "API Strategist",
  "Database Whisperer",
  "Streaming Systems Lead",
  "Realtime Architect",
  "Search Engineer",
  "Recommendation Crafter",
  "Privacy Engineer",
  "Security Strategist",
  "Cryptography Tinkerer",
  "Zero Trust Builder",
  "DevEx Advocate",
  "Developer Relations Pilot",
  "Hackathon Veteran",
  "Indie Hacker",
  "Studio Founder",
  "Growth Engineer",
  "Lifecycle Crafter",
  "Onboarding Architect",
  "Pricing Hacker",
  "Brand Technologist",
  "Community Builder",
  "Education Engineer",
  "Docs Cartographer",
  "Knowledge Architect",
  "Workflow Automator",
  "No Code Pioneer",
  "Low Code Strategist",
  "Visual Builder",
  "Creative Technologist",
  "Generative Artist",
  "Synthetic Media Maker",
  "Voice UX Crafter",
  "Conversational Designer",
  "Multimodal Engineer",
  "On-Device ML Hacker",
  "Federated Learning Lead",
  "Eval Engineer",
  "LLM Toolsmith",
  "Agent Architect",
  "RAG Strategist",
  "Vector DB Engineer",
  "Embeddings Crafter",
  "Fine Tune Pilot",
  "Inference Optimizer",
  "Model Compiler",
  "Quantization Hacker",
  "Silicon Whisperer",
  "GPU Scheduler",
  "Distributed Systems Lead",
  "Consensus Engineer",
  "Edge Cache Strategist",
  "CDN Architect",
  "Observability Builder",
  "Telemetry Crafter",
  "Incident Commander",
  "SRE Pathfinder",
  "Chaos Engineer",
  "Performance Hunter",
  "Core Web Vitals Lead",
  "Accessibility Advocate",
  "Inclusive Designer",
  "Motion Engineer",
  "3D Web Architect",
  "Spatial Computing Builder",
  "XR Pioneer",
  "Metaverse Cartographer",
  "Game Backend Builder",
  "Multiplayer Engineer",
  "Physics Simulator",
  "Procedural Generation Lead",
  "Pixel Crafter",
  "Typeface Hacker",
  "Type System Architect",
  "DSL Designer",
  "Compiler Engineer",
  "Runtime Builder",
  "Sandbox Architect",
  "WASM Voyager",
  "Container Crafter",
  "Orchestrator Pilot",
  "GitOps Strategist",
  "Infrastructure as Code Lead",
  "Policy Engineer",
  "FinOps Architect",
  "Carbon Aware Builder",
  "Sustainable Engineer",
  "Future of Work Hacker",
] as const;

/** Smooth cubic-bezier presets reused across Framer Motion variants. */
export const MOTION = {
  ease: [0.22, 1, 0.36, 1] as const,
  spring: { type: "spring", stiffness: 260, damping: 26, mass: 0.9 } as const,
} as const;
